# Generated by Django 4.2 on 2024-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customeruser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
