# Generated by Django 4.2 on 2024-07-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customeruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comeandwent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='come_and_went_records', to='api.customeruser'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.customeruser'),
        ),
    ]
